### ISSUE TITLE
blcd4-cd09: InFinite [CD] by Deep Purple (Musical group)【一起听-078期】

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#755]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1285172289&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd4/cd09/

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/imnWZ4qQu6usHBF6KNvcTw
