### ISSUE TITLE
i756/cd/: Bluegrass goes to town pop songs Buegrass style. [CD] :【一起听-027期】

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#756]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=168243868&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://littleflute.github.io/blshare1/blog/i756/cd/

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/u2ft74fW2q9TAsgW31c_3Q
