### ISSUE TITLE
blog/i758/ : Aqualung [CD] by Jethro Tull (Musical group)【一起听-026期】

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#758]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=9866433&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://littleflute.github.io/blshare1/blog/i758/

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/VtPcQQUz-VOC73ixQ-d1Iw
