### ISSUE TITLE
blcd1/cd04/: Cape Town flowers [CD] by Brand, Dollar【一起听-055期】

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#769]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1948850&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd1/cd04/

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/vs17UyzbNG35znkkz_A8Qw
