### ISSUE TITLE
blcd2-cd01: Blue & lonesome [CD] by Rolling Stones【一起听-056期】

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#770]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1178868019&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd2/cd01

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/7ClDVzS9khAmth8mqMMrqA
