### ISSUE TITLE
blcd2_cd04: Time's tales [CD] by Jeff Ballard Trio.【一起听-59期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#773]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=703190451&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd2/cd04

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/Q6FU3zJaJ3ZpkTii05bJBg
