### ISSUE TITLE
blcd2_cd05:Cisco Houston sings the songs of Woody Guthrie [CD]. by Houston, Cisco.【一起听-60期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#774]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1067759922&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd2/cd05

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/eOy9Z4QsIQTCSAi5qRu3vA
