### ISSUE TITLE
blcd2_cd06:From the muddy banks of the Wishkah [CD] by Nirvana (Musical group)【一起听-61期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#775]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=13050083&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd2/cd06

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/DvrY0RMSSwR42pLOGRE20Q
