### ISSUE TITLE
blcd2_cd08: Nirvana, unplugged in New York [CD] by Nirvana (Musical group)【一起听-63期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#777]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=6052017&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd2/cd08

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/bz6Pz1xuVbNiYH6v4s42hg
