### ISSUE TITLE
blcd2_cd09: Past light [CD] by Ackerman, Will【一起听-64期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#778]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=104539827&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd2/cd09

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/-Z99qtOho88Xp0pyCj7GEg
