### ISSUE TITLE
blcd3_cd01: Imaginary roads [CD] by Ackerman, Will【一起听-65期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#779]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=2311603&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd3/cd01

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s?__biz=MzA5MzMwNTc0Ng==&mid=2247488065&idx=1&sn=ee3eb3ace3f80c66bc99f79f6097f506&chksm=905ebcbca72935aaa220ddc8ab025377b2af393c1e577f02123612ab190f1d567628f15230f0&scene=21#wechat_redirect
