### ISSUE TITLE
blcd3_cd02: Chinese lullabies yüeh erh ming, feng erh ching / [CD] : (1995) By Yang, Xiulan.【一起听-66期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#780]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=230393598&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd3/cd02

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/avxlGPhSqV6gpR_o1fFxfQ
