### ISSUE TITLE
blcd3_cd03: Chinese festival gongs and drums for celebration III. [CD] :【一起听-67期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#781]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=3095021&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/qCbMk8AHo0HlrZSEMdc9xw

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd22/cd16
