### ISSUE TITLE
blcd3_cd05: West Side story original Broadway cast recording / [CD] : by Bernstein, Leonard【一起听-69期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#783]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=233455921&currentIndex=3&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/PbvcNHET2Yes4G2QrWt9TQ
