### ISSUE TITLE
blcd3_cd07:Blue valentine a love story / [CD] :【一起听-71期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#785]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1079355812&currentIndex=2&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/KL4I-R-WUhmkV1-tiwlGYw

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/szRF4ofg5pbXpJ_K-tmlog
