### ISSUE TITLE
blcd4_cd03: Back to the river [CD] by Tedeschi, Susan

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#787]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=8729803&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd4/cd03/

**Comment by littleflute** [comment]
【快乐分享005】一张专辑：Back to the river [CD] by Tedeschi, Susan
https://mp.weixin.qq.com/s/3yBNuPtHoOYfVchPd5BHwQ
