### ISSUE TITLE
blcd4_cd04:The best of the cutting edge 1965-1966 / [CD] : by Dylan, Bob【一起听-073期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#788]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=916518314&currentIndex=2&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/NV867TG5jKfvBzM1IX1NwA
