### ISSUE TITLE
blcd4_cd08:The essential Johnny Cash, 1955-1983 [CD] by Cash, Johnny.【一起听-077期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#792]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=498194&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/7ylz1uFGRtwHOIVaT3r4CQ
