### ISSUE TITLE
blcd18-cd08: Judy Collins sings Leonard Cohen democracy. [CD] : by Collins, Judy【一起听-044期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#793]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=4693766&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd18/cd08

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/4A7M4VCZGcqhYDQGvZgS7A

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd4/cd10
