### ISSUE TITLE
blcd18-cd09: Exodus [CD] by Marley, Bob.【一起听-045期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#794]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=199643371&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd18/cd09

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/U_wD4AzzvmzlUfzxHidTUQ
