### ISSUE TITLE
blcd22/cd22:Tibetan folk songs and dances [CD]. by Tibetan National Ensemble.【一起听-095期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#803]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=249371192&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd22/cds/cd22

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/X9Cnu9QSDALi4LtQwCKd_Q
