### ISSUE TITLE
Shot of love [CD] by Dylan, Bob

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#821]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=3850789&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd11/cd01

**Comment by littleflute** [comment]
https://en.wikipedia.org/wiki/Shot_of_Love#Songs

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/XjhPdw9WU8acNt6VO490Xg
