### ISSUE TITLE
All this time [CD] by Sting

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#823]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=3623779&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd11/cd02

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/JY_MVgcPZw9_gJYZ9ER7qQ
