### ISSUE TITLE
blcd11-cd03: The best of Fare thee well celebrating 50 years of Grateful Dead / [CD] : by Grateful Dead (Musical group)

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#824]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=819507554&currentIndex=2&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd11/cd03a
https://shanuan.github.io/blcd11/cd03b

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/O73MzGuwR4SUTqF3NjEl6g
