### ISSUE TITLE
blcd14-cd01: Metalocalypse the Dethalbum / [CD] : by Dethklok (Musical group)

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#850]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=234905285&currentIndex=0&view=fullDetailsDetailsTab

**Comment by shanuan** [comment]
https://shanuan.github.io/blcd14/cd01

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/5zjJ_TY6Gl6r7Z_GJjE2OA
