### ISSUE TITLE
blcd16-cd03: Dangerous curves [CD] by Golub, Jeff.【一起听-025期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#884]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1175701&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd16/cd03

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/sp05BO-fdyWw73sis78N3A
