### ISSUE TITLE
blcd16-cd04: Brothers [CD] by Black Keys (Musical group)【一起听-033期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#885]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=91736659&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd16/cd04

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/4pUn7eJYYW77sgxpX2QijA
