### ISSUE TITLE
blcd17-cd04: Blood red roses [CD]【一起听-035期】

### ISSUE THREAD

**Issue by littleflute** [littleflute/blog#897]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1700438953&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd17/cd04

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/JKZ3l7Pbc4jpaw4v-a7q1A
