### ISSUE TITLE
blcd19-cd06: Montana, a love story solo piano / [CD] : by Winston, George.【一起听-051期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#919]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=1332989&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://www.youtube.com/watch?v=AfIgzMT81w0

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd19/cd06
