### ISSUE TITLE
blcd22/cd21:Now that's what I call rock [CD]【一起听-094期】

### ISSUE THREAD

**Issue by shanuan** [littleflute/blog#930]
https://library.ci.corvallis.or.us/?id=26928003301282#section=resource&resourceid=941259731&currentIndex=0&view=fullDetailsDetailsTab

**Comment by littleflute** [comment]
https://shanuan.github.io/blcd22/cds/cd21/

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/_ZRtwUAK2NkL-W4CiGCnnQ
